<!--
document.writeln("<script type=\"text/javascript\">");
document.writeln("var uniqId = new Date();");
document.writeln("var uniqStr = uniqId.getHours()+\'\'+uniqId.getMinutes()+\'\'+uniqId.getSeconds()");
document.writeln("var adUri = \'http://www.sponsorads.de/werbemedien/picturelayer/chicago1920/aufruf.php?\'+uniqStr;");
document.writeln("var linkedUri = \'http://www.sponsorads.de/b_click.php?u=4454&s=115833&c=2264&h=8c40456c7de7c33a0bf801b658228162\'");
document.writeln("var upHeader = \'Chicago1920.com das neue Mafia Game !\';");
document.writeln("eval(\"var uniqueImage\"+uniqStr+\" = \"+\"new Image()\");");
document.writeln("eval(\"uniqueImage\"+uniqStr).src = adUri;");
document.writeln("popupx(adUri);");
document.writeln("var time = 0;");
document.writeln("var opened = 0;");
document.writeln("function showx(div){");
document.writeln("if (opened == 0) {");
document.writeln("     opened = 1;");
document.writeln("  x=document.getElementById(div);");
document.writeln("  x.style.width = eval(\"uniqueImage\"+uniqStr).width+\'px\';");
document.writeln("  //x.style.height = eval(\"uniqueImage\"+uniqStr).height + 47;");
document.writeln("  var procent = Math.round((((document.body.clientWidth - eval(\"uniqueImage\"+uniqStr).width)/2)/document.body.clientWidth)*100);");
document.writeln("  x.style.marginLeft = procent + \'%\';");
document.writeln("  temp1=document.getElementById(\'downbar46554\');");
document.writeln("  temp2=document.getElementById(\'upbar46554\');");
document.writeln("  temp1.style.width = eval(\"uniqueImage\"+uniqStr).width+\'px\';");
document.writeln("  temp2.style.width = eval(\"uniqueImage\"+uniqStr).width+\'px\';");
document.writeln("    x.style.display = \'block\';");
document.writeln("}  }");
document.writeln("function closepopx(){");
document.writeln("  x=document.getElementById(\'sponsorads46554b\');");
document.writeln("  x.style.display=\'none\';");
document.writeln("}");
document.writeln("function openpopx(uri,mode){");
document.writeln("WindowObjectReference = window.open(uri,\"adWindow\",\"\");");
document.writeln("if(mode==0){");
document.writeln("  self.focus();");
document.writeln("  window.focus();");
document.writeln("}");
document.writeln("closepopx();");
document.writeln("}");
document.writeln("function addBookmark(title,url) {");
document.writeln("if (window.sidebar) {");
document.writeln("window.sidebar.addPanel(title, url,\"\");");
document.writeln("} else if( document.all ) {");
document.writeln("window.external.AddFavorite( url, title);");
document.writeln("} else if( window.opera && window.print ) {");
document.writeln("return true;");
document.writeln("}");
document.writeln("}");
document.writeln("function spSetOpacity(x, opacity)");
document.writeln("{");
document.writeln("	opacity = (opacity == 100)?99.999:opacity;");
document.writeln("	x.style.filter = \"alpha(opacity:\"+opacity+\")\";");
document.writeln("	x.style.khtmlopacity = opacity/100;");
document.writeln("	x.style.mozopacity = opacity/100;");
document.writeln("	x.style.opacity = opacity/100;");
document.writeln("	x.style.operacity = opacity/100;");
document.writeln("}");
document.writeln("function spFadeIn(x)");
document.writeln("{");
document.writeln("    spCurrentOpacity += 15;");
document.writeln("    spSetOpacity(x, spCurrentOpacity);");
document.writeln("    if(spCurrentOpacity < 100)");
document.writeln("        window.setTimeout(\'spFadeIn(x)\', 1);");
document.writeln("}");
document.writeln("function spFadeOut(x)");
document.writeln("{");
document.writeln("    spCurrentOpacity -= 25;");
document.writeln("    spSetOpacity(x, spCurrentOpacity);");
document.writeln("    if(spCurrentOpacity > 0)");
document.writeln("        window.setTimeout(\'spFadeOut(x)\', 1);");
document.writeln("    else");
document.writeln("        x.style.display = \"none\";");
document.writeln("}");
document.writeln("imgx1_hov = new Image();");
document.writeln("imgx1_hov.src = \"http://imgserv.sponsorads.de/images/layer/x1_hov.png\";");
document.writeln("imgx2_hov = new Image();");
document.writeln("imgx2_hov.src = \"http://imgserv.sponsorads.de/images/layer/x2_hov.png\";");
document.writeln("imgx3_hov = new Image();");
document.writeln("imgx3_hov.src = \"http://imgserv.sponsorads.de/images/layer/x3_hov.png\";");
document.writeln("imgx4_hov = new Image();");
document.writeln("imgx4_hov.src = \"http://imgserv.sponsorads.de/images/layer/x4_hov.png\";");
document.writeln("imgx5_hov = new Image();");
document.writeln("imgx5_hov.src = \"http://imgserv.sponsorads.de/images/layer/x5_hov.png\";");
document.writeln("imgx1 = new Image();");
document.writeln("imgx1.src = \"http://imgserv.sponsorads.de/images/layer/x1.png\";");
document.writeln("imgx2 = new Image();");
document.writeln("imgx2.src = \"http://imgserv.sponsorads.de/images/layer/x2.png\";");
document.writeln("imgx3 = new Image();");
document.writeln("imgx3.src = \"http://imgserv.sponsorads.de/images/layer/x3.png\";");
document.writeln("imgx4 = new Image();");
document.writeln("imgx4.src = \"http://imgserv.sponsorads.de/images/layer/x4.png\";");
document.writeln("imgx5 = new Image();");
document.writeln("imgx5.src = \"http://imgserv.sponsorads.de/images/layer/x5.png\";");
document.writeln("function swapOn(id,src){");
document.writeln("theImg=document.getElementById(id);");
document.writeln("theImg.setAttribute(\"src\",src);");
document.writeln("}");
document.writeln("function swapOff(id,src){");
document.writeln("theImg=document.getElementById(id);");
document.writeln("theImg.setAttribute(\"src\",src);");
document.writeln("}");
document.writeln("function popupx(url){");
document.writeln("      document.write(\'<div id=\"sponsorads46554b\" style=\"\');");
document.writeln("        document.write(\'position:fixed;\');");
document.writeln("        document.write(\'_position:absolute;\');");
document.writeln("        document.write(\'left:0;\');");
document.writeln("        document.write(\'top:10px;\');");
document.writeln("        document.write(\'_top: expression(10+(ignoreMe = document.documentElement.scrollTop ? document.documentElement.scrollTop : document.body.scrollTop));\');");
document.writeln("        document.write(\'display:none;\');");
document.writeln("        document.write(\'background:#fff;\');");
document.writeln("        document.write(\'border:1px solid #0C375F;\');");
document.writeln("        document.write(\'z-index:1000;\');");
document.writeln("      document.write(\'\">\');");
document.writeln("      document.write(\'<div id=\"upbar46554\" style=\"\');");
document.writeln("        document.write(\'height:23px;\');");
document.writeln("        document.write(\'background:#aaa url(http://imgserv.sponsorads.de/images/layer/wrap.gif) repeat-x;\');");
document.writeln("        document.write(\'border-bottom:1px solid #0C375F;\');");
document.writeln("        document.write(\'text-align:right;\');");
document.writeln("      document.write(\'\">\');");
document.writeln("      document.write(\'<span id=\"uptitle\" style=\"\');");
document.writeln("        document.write(\'color:#000;\');");
document.writeln("        document.write(\'font-weight:normal;\');");
document.writeln("        document.write(\'height:20px;\');");
document.writeln("        document.write(\'_height:17px;\');");
document.writeln("        document.write(\'float:left;\');");
document.writeln("        document.write(\'padding-left:35px;\');");
document.writeln("        document.write(\'margin-top:2px;\');");
document.writeln("        document.write(\'font-size:11px;\');");
document.writeln("        document.write(\'line-height:20px;\');");
document.writeln("        document.write(\'font-family:Tahoma,Helvetica,Arial,sans-serif;\');");
document.writeln("        document.write(\'background-image:url(http://imgserv.sponsorads.de/images/layer/arrow.png);\');");
document.writeln("        document.write(\'background-repeat:no-repeat;\');");
document.writeln("        document.write(\'background-position:5px 0;\');");
document.writeln("      document.write(\'\">\');");
document.writeln("      document.write(\'<a style=\"text-decoration:none; color:#2B3844;\" href=\"\'+linkedUri+\'\">\'+upHeader+\'</a>\');");
document.writeln("      document.write(\'</span>\');");
document.writeln("      document.write(\'<a href=\"#\" onclick=\"openpopx(linkedUri,0)\" title=\"Später ansehen - Im Hintergrund öffnen\">\');");
document.writeln("      document.write(\'<img id=\"imx4\" style=\"border:none;padding-right:6px;margin-top:2px;\" src=\"http://imgserv.sponsorads.de/images/layer/x4.png\" onmouseover=\"swapOn(\\\'imx4\\\',imgx4_hov.src);\" onmouseout=\"swapOff(\\\'imx4\\\',imgx4.src);\" />\');");
document.writeln("      document.write(\'</a>\');");
document.writeln("      document.write(\'<a href=\"#\" onclick=\"closepopx(); return false\" title=\"Fenster schliessen\">\');");
document.writeln("      document.write(\'<img id=\"imx3\" style=\"border:none;padding-right:2px;margin-top:2px;\" src=\"http://imgserv.sponsorads.de/images/layer/x3.png\" alt=\"Fenster schliessen\" onmouseover=\"swapOn(\\\'imx3\\\',imgx3_hov.src);\" onmouseout=\"swapOff(\\\'imx3\\\',imgx3.src);\" />\');");
document.writeln("      document.write(\'</a>\');");
document.writeln("      document.write(\'</div>\');");
document.writeln("      document.write(\'<a href=\"\'+linkedUri+\'\" target=\"_blank\" onclick=\"openpopx(linkedUri,1);return false;\"><img onload=\"showx(\\\'sponsorads46554b\\\');\" style=\"display:block;border:none;margin:0;padding:0;\" id=\"popWindow\" name=\"popWindow\" src=\"\'+url+\'\" /></a>\');");
document.writeln("      document.write(\'<div id=\"downbar46554\" style=\"\');");
document.writeln("        document.write(\'margin-top:0px;\');");
document.writeln("        document.write(\'height:22px;\');");
document.writeln("        document.write(\'background:#aaa url(http://imgserv.sponsorads.de/images/layer/wrap.gif) repeat-x;\');");
document.writeln("        document.write(\'border-top:1px solid #0C375F;\');");
document.writeln("        document.write(\'text-align:right;\');");
document.writeln("      document.write(\'\">\');");
document.writeln("      document.write(\'<span id=\"downtitle\" style=\"\');");
document.writeln("        document.write(\'color:#2B3844;\');");
document.writeln("        document.write(\'font-weight:normal;\');");
document.writeln("        document.write(\'float:left;\');");
document.writeln("        document.write(\'height:18px;\');");
document.writeln("         document.write(\'padding-left:5px;\');");
document.writeln("        document.write(\'padding-top:3px;\');");
document.writeln("      document.write(\'\">\');");
document.writeln("      document.write(\'<a target =\"_blank\" href=\"http://www.sponsorads.de\" title=\"SponsorAds - Das grosse Werbenetzwerk\"><img style=\"border:none;padding-right:2px;\" src=\"http://imgserv.sponsorads.de/images/layer/sponsorads.gif\" /></a>\');");
document.writeln("      document.write(\'</span>\');");
document.writeln("      document.write(\'</div>\');");
document.writeln("  document.write(\'</div>\');");
document.writeln("}");
document.writeln("</script>");
// -->